# -*- coding: utf-8 -*-
"""Face Mask Detection.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wB9MCEhS0DXI34ApOh1SDjySaMnmuri6
"""

!mkdir datasets

!curl -L -q "https://app.roboflow.com/ds/4xSphAbbqR?key=pEu2BwBElX" > datasets/roboflow.zip; unzip -q datasets/roboflow.zip  -d datasets/; rm datasets/roboflow.zip

from google.colab import drive
drive.mount('/content/drive')

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/drive/MyDrive/yolov5

!pip install -qr requirements.txt
!pip install -q wandb

import torch
import os
from IPython.display import clear_output, Image

print(f"Setup complete. Using torch {torch.__version__} ({torch.cuda.get_device_properties(0).name if torch.cuda.is_available() else 'CPU'})")

# set up environment
os.environ["DATASET_DIRECTORY"] = "/content/datasets"

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/drive/MyDrive/yolov5

!python train.py --img 416 --batch 16 --epochs 150 --data /content/datasets/data.yaml --weights yolov5s.pt --cache

!python detect.py --weights runs/train/exp14/weights/best.pt --img 416 --conf 0.6 --line-thickness 1 --source /content/datasets/test/images

#display inference on ALL test images

import glob
from IPython.display import Image, display

for imageName in glob.glob('/content/drive/MyDrive/yolov5/runs/detect/exp4/*.jpg'): #assuming JPG
    display(Image(filename=imageName))
    print("\n")

# #export your model's weights for future use
# from google.colab import files
# files.download('./runs/train/exp5/weights/best.pt')

!python detect.py --weights runs/train/exp14/weights/best.pt --img 416 --conf 0.6 --line-thickness 1 --source /content/People_wear_mask_in_Causeway_Bay_202001.png

display(Image(filename='/content/drive/MyDrive/yolov5/runs/detect/exp5/People_wear_mask_in_Causeway_Bay_202001.png'))

